# Generated by Django 5.1.6 on 2025-02-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='cell',
            name='spreadsheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.spreadsheet'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('spreadsheet', 'row', 'column')},
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
